### ISSUE TITLE
Amount must be at least 0.01. Requesting createLoanOffer

### ISSUE THREAD

**Issue by btjholden** [Mikadily/poloniexlendingbot#199] opened 2017-01-21 22:26 UTC
Receiving the following error can you help please?

Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/cornelius/lendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/cornelius/lendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/cornelius/lendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/cornelius/lendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/cornelius/lendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/cornelius/lendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!

**Comment by Nithanim** [comment] 2017-01-21 23:55
Duplicate of  #180

**Closed** 2017-01-22 00:05 UTC
