### ISSUE TITLE
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

### ISSUE THREAD

**Issue by daedalus** [Mikadily/poloniexlendingbot#191] opened 2017-01-16 22:41 UTC
I already have more than 0.01 LTC, and I think this is not a duplicated bug of #185
My repo is up to date.
```
2017-01-16 20:34:02 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "code/BTC/poloniexlendingbot/lendingbot.py", line 69, in <module>
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/dclavijo/code/BTC/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment] 2017-01-17 01:50
Hey, can you run the lending-rewrite branch for me and tell me if you continue to receive the error? 
This may already be solved and a duplicate of #180

**Comment by daedalus** [comment] 2017-01-17 19:00
It runs ok with the lending-rewrite branch.
Thanks

**Comment by Evanito** [comment] 2017-01-17 22:17
Just pushed a bugfix to #180 
Give it a shot

**Comment by NeuralMiner** [comment] 2017-01-18 17:12
`lending-rewrite` looks to have fixed it for me, but now it seems like the bot isn't respecting the global mindailyrate set in the cfg.
`mindailyrate = 0.02`
Trades placed:

> BTC	0.0183%	
> BTC	0.0183%	
> BTC	0.0183%	

I have a custom coin config for MAID:
`coinconfig = ["MAID:0.2:1:0:0:0"]`

> MAID	0.0956%
> MAID	0.0918%	
> MAID	0.0879%	
> MAID	0.1097%	

It was working correctly on `master`.

**Comment by daedalus** [comment] 2017-01-18 19:57
Solved
Thanks

**Closed** 2017-01-18 22:40 UTC
Labels: Troubleshooting

**Comment by Evanito** [comment] 2017-01-18 23:48
@NeuralMiner Should be fixed in recent `lending-rewrite` bugfix, please confirm and make a new issue if it isn't completely fixed.

**Comment by NeuralMiner** [comment] 2017-01-19 16:58
Thanks @Evanito. I'll give it a test and create a new issue if it doesnt work.
