### ISSUE TITLE
percentile() got an unexpected keyword argument 'interpolation'

### ISSUE THREAD

**Issue by mikemr** [Mikadily/poloniexlendingbot#186] opened 2017-01-14 08:20 UTC
```
Error: percentile() got an unexpected keyword argument 'interpolation'
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/root/bot/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/root/bot/poloniexlendingbot/modules/Lending.py", line 163, in lend_cur
    recommended_min = Analysis.get_rate_suggestion(active_cur)
  File "/root/bot/poloniexlendingbot/modules/MarketAnalysis.py", line 118, in get_rate_suggestion
    result = numpy.percentile(rates, int(percentile), interpolation='linear')
TypeError: percentile() got an unexpected keyword argument 'interpolation'

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment] 2017-01-14 08:22
Duplicate of #184 
Please see solution there.

**Closed by Evanito** 2017-01-14 08:22 UTC
Labels: Duplicate, Troubleshooting
