### ISSUE TITLE
Ringbuffer buggy 

### ISSUE THREAD

**Issue by TamtamHero** [Mikadily/poloniexlendingbot#162] opened 2016-12-12 19:28 UTC
The RingBuffer is currently interpreting its "size" parameter as a string.
Writing "jsonlogsize 50" doesn't give a buffer of size 50.

I quick fixed it in the RingBuffer.py file, by casting "size" as int(size) in the constructor.
Could someone fix this ?

Thanks !

**Comment by Evanito** [comment] 2016-12-15 23:30
This issue is not present, the config passes the value as an int. You can test this yourself by inserting 
`print type(Config.get('BOT', 'jsonlogsize', -1))` 
at any point after the config is initialized. 

The problem seems to be that you have `jsonlogsize 50` in your config instead of `jsonlogsize = 50`

Closing because I am unable to reproduce error, feel free to reopen if I haven't solved your problem.

**Closed by Evanito** 2016-12-15 23:30 UTC
