### ISSUE TITLE
URLError

### ISSUE THREAD

**Issue by sanitariu** [Mikadily/poloniexlendingbot#179] opened 2017-01-08 10:41 UTC
```
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
2017-01-08 12:17:19 Error: <urlopen error  Requesting returnActiveLoans>
Traceback (most recent call last):
  File "lendingbot.py", line 66, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Data.py", line 80, in update_conversion_rates
    total_lended = get_total_lended()[0]
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Data.py", line 42, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 135, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 79, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error  Requesting returnActiveLoans>

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment] 2017-01-08 11:33
Thank you for the bug report, seems to be an error somewhere between your computer and Poloniex's API. We are looking into handling these gracefully.

**Comment by ChrisG2711** [comment] 2017-01-16 17:09
Guess I´m seeing the same error leading to the strange behaviour of ignoring my CLAM, without any message in webserver. When placing them manually via Polo they are cancelled (no message on webserver too) but not getting lended by bot. Amount is above limit, also the lending rates are very high today.

**Comment by trideceth12** [comment] 2017-01-26 00:35
I get the same exception all the time as well
* It's hard to tell if the bot is still working after this exception
* The webserver doesn't show the status after this exception

> 2017-01-26 11:32:14 Error: <urlopen error  Requesting returnActiveLoans>
Traceback (most recent call last):
  File "lendingbot.py", line 66, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/home/manko/Repos/monero/poloniexlendingbot/modules/Data.py", line 80, in update_conversion_rates
    total_lended = get_total_lended()[0]
  File "/home/manko/Repos/monero/poloniexlendingbot/modules/Data.py", line 42, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "/home/manko/Repos/monero/poloniexlendingbot/modules/Poloniex.py", line 135, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "/home/manko/Repos/monero/poloniexlendingbot/modules/Poloniex.py", line 79, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error  Requesting returnActiveLoans>

**Comment by rnevet** [comment] 2017-01-28 21:54
@trideceth12 Keyboard interrupt issue should be resolved with latest update.

**Comment by geostoned** [comment] 2017-02-06 15:19
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
2017-02-06 05:59:39 Error: <urlopen error  Requesting returnActiveLoans>
Traceback (most recent call last):
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\lendingbot.py", line 68, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Data.py", line 82, in update_conversion_rates
    total_lended = get_total_lended()[0]
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Data.py", line 44, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Poloniex.py", line 160, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error  Requesting returnActiveLoans>

Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment] 2017-03-07 22:33
This is probably caused by an issue on Poloniex side, in any case the bot should continue after sleeping, please open a new issue if Bot operation is somehow effected.

**Closed by rnevet** 2017-03-07 22:33 UTC
Labels: Poloniex's Fault
