### ISSUE TITLE
BTC Estimated Earnings not updating

### ISSUE THREAD

**Issue by AlexMinty** [Mikadily/poloniexlendingbot#71] opened 2016-05-20 04:31 UTC
Running on a Linux VPS with webserver active.

Only get an initial snapshot of estimated earnings when starting the bot. Status 'Lended' updates fine but everything below that is static. Reversed ordered Log updates fine. Only lending BTC.

**Comment by Evanito** [comment] 2016-05-20 04:34
Does refreshing the page update what you find static?

**Comment by AlexMinty** [comment] 2016-05-20 04:34
No it does not. I also tried different web browsers.

**Comment by Evanito** [comment] 2016-05-20 04:36
You find that the coin summary for BTC doesn't match the Status 'Lended' description of what you have lended?

**Comment by AlexMinty** [comment] 2016-05-20 04:38
Correct. 'Active Loans'	'Average Loan Interest Rate'	  'Total Effective Interest Rate' are just static

**Comment by Evanito** [comment] 2016-05-20 04:40
That's curious since the HTML file is updated entirely from the .json each time the page is loaded.

I will run the bot for a while and attempt to recreate the issue, since @rnevet did the code for it he may have a solution sooner.

**Comment by AlexMinty** [comment] 2016-05-20 04:42
I'm going to nuke the current install and start fresh. Will let you know in a couple of minutes

**Comment by AlexMinty** [comment] 2016-05-20 04:55
fresh install done, lended out some BTC, and same issue persists. For some reason the json file is not updating the coin summary

**Comment by rnevet** [comment] 2016-05-20 06:46
i can confirm the issue, looking into it.

**Comment by rnevet** [comment] 2016-05-20 07:10
Should be fixed with latest update: https://github.com/Mikadily/poloniexlendingbot/pull/72

**Comment by AlexMinty** [comment] 2016-05-20 07:44
nice one, installed new logger.py and everything is updating as it should.

**Closed** 2016-05-20 08:01 UTC
Labels: Bug
