### ISSUE TITLE
error first run after config set please advvise

### ISSUE THREAD

**Issue by btcunbranded** [Mikadily/poloniexlendingbot#250] opened 2017-03-08 00:29 UTC
Welcome to Poloniex Lending Bot
2017-03-08 00:28:35 Error: HTTP Error 403: Forbidden Requesting returnOpenLoanOffers
Traceback (most recent call last):
  File "C:\polo\poloniexlendingbot-master\lendingbot.py", line 71, in <module>
    Lending.cancel_all()
  File "C:\polo\poloniexlendingbot-master\modules\Lending.py", line 138, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "C:\polo\poloniexlendingbot-master\modules\Poloniex.py", line 153, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "C:\polo\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

Unhandled error, please open a Github issue so we can fix it!

**Comment by laxdog** [comment] 2017-03-08 06:28
Dupe of https://github.com/Mikadily/poloniexlendingbot/issues/242

Same questions:

Have you had it working from this computer before?
Have you used this API key with the bot before?
Can you access poloniex.com through a browser?

This is unlikely to be an issue on the bot. It's probably a problem with your Polo setup, or firewall or something. Please check your Polo keys are setup properly.

**Comment by btcunbranded** [comment] 2017-03-11 18:48
Thankyou very much.will reinstall and check my system, then report back

**Comment by rnevet** [comment] 2017-03-15 12:12
@btcunbranded is the issue resolved?

**Closed** 2017-04-02 08:33 UTC
Labels: Duplicate
