### ISSUE TITLE
Error: Please do not make more than 6 API calls per second

### ISSUE THREAD

**Issue by mikemr** [Mikadily/poloniexlendingbot#187] opened 2017-01-14 08:42 UTC
```
python lendingbot.py 
WARNING: Module Numpy not found, using manual percentile method. It is recommended to install Numpy. Error: No module named numpy
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
2017-01-14 08:40:30 Error: Please do not make more than 6 API calls per second. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/root/bot/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/root/bot/poloniexlendingbot/modules/Lending.py", line 218, in lend_cur
    create_lend_offer(active_cur, Decimal(active_bal) - lent, offer['rate'])
  File "/root/bot/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/root/bot/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/root/bot/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/root/bot/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Please do not make more than 6 API calls per second. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment] 2017-01-14 08:55
Hey mike,
Duplicate of #167 
You did just inspire me of how to create a fix, though.

**Closed by Evanito** 2017-01-14 08:55 UTC
Labels: Bug, Duplicate
